import { contextBridge, ipcRenderer } from "electron";
import type { GitAPI, UpdateState } from "../src/types";

const api: GitAPI = {
  isRepo: (repoPath: string) => ipcRenderer.invoke("git:is-repo", repoPath),
  branches: (repoPath: string) => ipcRenderer.invoke("git:branches", repoPath),
  log: (repoPath: string, skip: number, maxCount: number) => ipcRenderer.invoke("git:log", repoPath, skip, maxCount),
  status: (repoPath: string) => ipcRenderer.invoke("git:status", repoPath),
  show: (repoPath: string, hash: string) => ipcRenderer.invoke("git:show", repoPath, hash),
  lastMessage: (repoPath: string) => ipcRenderer.invoke("git:last-message", repoPath),
  stage: (repoPath: string, files: string[]) => ipcRenderer.invoke("git:stage", repoPath, files),
  unstage: (repoPath: string, files: string[]) => ipcRenderer.invoke("git:unstage", repoPath, files),
  discard: (repoPath: string, files: string[]) => ipcRenderer.invoke("git:discard", repoPath, files),
  commit: (repoPath: string, message: string, amend: boolean) => ipcRenderer.invoke("git:commit", repoPath, message, amend),
  checkout: (repoPath: string, branch: string) => ipcRenderer.invoke("git:checkout", repoPath, branch),
  checkoutRemote: (repoPath: string, remoteBranch: string) => ipcRenderer.invoke("git:checkout-remote", repoPath, remoteBranch),
  createBranch: (repoPath: string, branchName: string, checkout: boolean) => ipcRenderer.invoke("git:create-branch", repoPath, branchName, checkout),
  deleteBranch: (repoPath: string, branchName: string, force: boolean) => ipcRenderer.invoke("git:delete-branch", repoPath, branchName, force),
  merge: (repoPath: string, branchName: string) => ipcRenderer.invoke("git:merge", repoPath, branchName),
  reset: (repoPath: string, commitHash: string, mode: "soft" | "mixed" | "hard") => ipcRenderer.invoke("git:reset", repoPath, commitHash, mode),
  stashSave: (repoPath: string, message?: string) => ipcRenderer.invoke("git:stash-save", repoPath, message),
  stashList: (repoPath: string) => ipcRenderer.invoke("git:stash-list", repoPath),
  stashPop: (repoPath: string, ref?: string) => ipcRenderer.invoke("git:stash-pop", repoPath, ref),
  stashDrop: (repoPath: string, ref: string) => ipcRenderer.invoke("git:stash-drop", repoPath, ref),
  fetch: (repoPath: string) => ipcRenderer.invoke("git:fetch", repoPath),
  pull: (repoPath: string) => ipcRenderer.invoke("git:pull", repoPath),
  push: (repoPath: string) => ipcRenderer.invoke("git:push", repoPath),
  openDirectory: () => ipcRenderer.invoke("dialog:open-directory"),
  openGitBash: (repoPath: string) => ipcRenderer.invoke("shell:open-git-bash", repoPath),
  diffFile: (repoPath: string, filePath: string, staged: boolean) => ipcRenderer.invoke("git:diff-file", repoPath, filePath, staged),
  commitFileDiff: (repoPath: string, hash: string, filePath: string) => ipcRenderer.invoke("git:commit-file-diff", repoPath, hash, filePath),
  stageHunk: (repoPath: string, patchContent: string) => ipcRenderer.invoke("git:stage-hunk", repoPath, patchContent),
  unstageHunk: (repoPath: string, patchContent: string) => ipcRenderer.invoke("git:unstage-hunk", repoPath, patchContent),
  revertHunk: (repoPath: string, patchContent: string) => ipcRenderer.invoke("git:revert-hunk", repoPath, patchContent),
  getConfig: (repoPath: string) => ipcRenderer.invoke("git:get-config", repoPath),
  setConfig: (repoPath: string, key: string, value: string) => ipcRenderer.invoke("git:set-config", repoPath, key, value),
  getSettings: () => ipcRenderer.invoke("settings:get-all"),
  setSetting: (key: string, value: unknown) => ipcRenderer.invoke("settings:set", key, value),
  minimizeWindow: () => ipcRenderer.invoke("window:minimize"),
  maximizeWindow: () => ipcRenderer.invoke("window:maximize"),
  closeWindow: () => ipcRenderer.invoke("window:close"),
  isMaximized: () => ipcRenderer.invoke("window:is-maximized"),
  getUpdateState: () => ipcRenderer.invoke("update:get-state"),
  checkForUpdates: () => ipcRenderer.invoke("update:check"),
  downloadUpdate: () => ipcRenderer.invoke("update:download"),
  installUpdate: () => ipcRenderer.invoke("update:install"),
  onUpdateEvent: (cb: (state: UpdateState) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, state: UpdateState) => cb(state);
    ipcRenderer.on("update:event", listener);
    return () => { ipcRenderer.removeListener("update:event", listener); };
  },
  clone: (url, destPath, branch) => ipcRenderer.invoke("git:clone", url, destPath, branch),
  fileHistory: (repoPath, filePath, maxCount) => ipcRenderer.invoke("git:file-history", repoPath, filePath, maxCount),
  blame: (repoPath, filePath, hash) => ipcRenderer.invoke("git:blame", repoPath, filePath, hash),
  revertCommit: (repoPath, hash) => ipcRenderer.invoke("git:revert", repoPath, hash),
  compare: (repoPath, fromRef, toRef) => ipcRenderer.invoke("git:compare", repoPath, fromRef, toRef),
  compareFileDiff: (repoPath, fromRef, toRef, filePath) => ipcRenderer.invoke("git:compare-file-diff", repoPath, fromRef, toRef, filePath),
  cherryPick: (repoPath, hash) => ipcRenderer.invoke("git:cherry-pick", repoPath, hash),
  rebase: (repoPath, upstream) => ipcRenderer.invoke("git:rebase", repoPath, upstream),
  rebaseAbort: (repoPath) => ipcRenderer.invoke("git:rebase-abort", repoPath),
  tags: (repoPath) => ipcRenderer.invoke("git:tags", repoPath),
  createTag: (repoPath, name, ref, message) => ipcRenderer.invoke("git:create-tag", repoPath, name, ref, message),
  deleteTag: (repoPath, name) => ipcRenderer.invoke("git:delete-tag", repoPath, name),
  remotes: (repoPath) => ipcRenderer.invoke("git:remotes", repoPath),
  addRemote: (repoPath, name, url) => ipcRenderer.invoke("git:add-remote", repoPath, name, url),
  removeRemote: (repoPath, name) => ipcRenderer.invoke("git:remove-remote", repoPath, name),
  setRemoteUrl: (repoPath, name, url) => ipcRenderer.invoke("git:set-remote-url", repoPath, name, url),
  hostingUrl: (repoPath, ref) => ipcRenderer.invoke("git:hosting-url", repoPath, ref),
  openExternal: (url) => ipcRenderer.invoke("shell:open-external", url),
  readGitignore: (repoPath) => ipcRenderer.invoke("git:read-gitignore", repoPath),
  writeGitignore: (repoPath, content) => ipcRenderer.invoke("git:write-gitignore", repoPath, content),
  mergetool: (repoPath, filePath) => ipcRenderer.invoke("git:mergetool", repoPath, filePath),
};

contextBridge.exposeInMainWorld("gitAPI", api);
